name: Doxygen Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create directory
        run: mkdir -p build/doxygen/html/

      - uses: mattnotmitt/doxygen-action@v1.12.0
        with:
          doxyfile-path: 'documentation/doxygen/doxyfile'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doxygen/html/
          publish_branch: gh-pages